module CoaxProbe 
    export coaxprobe
    using LaTeXStrings  
    function coaxprobe(ProjectName::String, VBSfilePath::String, XPosition::Float64, YPosition::Float64, CoaxRadius::Float64, PinRadius::Float64, CoaxHeight::Float64, SubstrateHeight::Float64)
        file = open("$(VBSfilePath)\\CoaxProbe.vbs", "w")
        write(file, "Dim oAnsoftApp\n")
        write(file, "Dim oDesktop\n")
        write(file, "Dim oProject\n")
        write(file, "Dim oDesign\n")
        write(file, "Dim oEditor\n")
        write(file, "Dim oModule\n")
        write(file, "Set oAnsoftApp = CreateObject(\"Ansoft.ElectronicsDesktop\")\n")
        write(file, "Set oDesktop = oAnsoftApp.GetAppDesktop()\n")
        write(file, "oDesktop.RestoreWindow\n")
        write(file, "Set oProject = oDesktop.SetActiveProject(\"$(ProjectName)\")\n")
        write(file, "Set oDesign = oProject.SetActiveDesign(\"HFSSDesign1\")\n")
        write(file, "Set oEditor = oDesign.SetActiveEditor(\"3D Modeler\")\n")
        write(file, "oEditor.CreateCylinder Array(\"NAME:CylinderParameters\", \"XCenter:=\", \"$(XPosition)mm\", \"YCenter:=\",  _\n")
        write(file, "\"$(YPosition)mm\", \"ZCenter:=\", \"0mm\", \"Radius:=\", \"$(CoaxRadius)mm\", \"Height:=\",  _\n")
        write(file, "\"-$(CoaxHeight)mm\", \"WhichAxis:=\", \"Z\", \"NumSides:=\", \"0\"), Array(\"NAME:Attributes\", \"Name:=\",  _\n")
        write(file, "\"Cylinder1\", \"Flags:=\", \"\", \"Color:=\", \"(143 175 143)\", \"Transparency:=\", 0, \"PartCoordinateSystem:=\",  _\n")
        write(file, "\"Global\", \"UDMId:=\", \"\", \"MaterialValue:=\", \"\" & Chr(34) & \"polyethylene\" & Chr(34) & \"\", \"SurfaceMaterialValue:=\",  _\n")
        write(file, "\"\" & Chr(34) & \"\" & Chr(34) & \"\", \"SolveInside:=\", true, \"ShellElement:=\",  _\n")
        write(file, "false, \"ShellElementThickness:=\", \"0mm\", \"IsMaterialEditable:=\", true, \"UseMaterialAppearance:=\",  _\n")
        write(file, "false, \"IsLightweight:=\", false)\n")
        write(file, "oEditor.ChangeProperty Array(\"NAME:AllTabs\", Array(\"NAME:Geometry3DAttributeTab\", Array(\"NAME:PropServers\",  _\n")
        write(file, "\"Cylinder1\"), Array(\"NAME:ChangedProps\", Array(\"NAME:Name\", \"Value:=\", \"Coax\"), Array(\"NAME:Transparent\", \"Value:=\",  _\n")
        write(file, "0.7))))\n")
        write(file, "oEditor.CreateCylinder Array(\"NAME:CylinderParameters\", \"XCenter:=\", \"$(XPosition)mm\", \"YCenter:=\",  _\n")
        write(file, "\"$(YPosition)mm\", \"ZCenter:=\", \"0mm\", \"Radius:=\", \"$(PinRadius)mm\", \"Height:=\",  _\n")
        write(file, "\"-$(CoaxHeight)mm\", \"WhichAxis:=\", \"Z\", \"NumSides:=\", \"0\"), Array(\"NAME:Attributes\", \"Name:=\",  _\n")
        write(file, "\"Cylinder1\", \"Flags:=\", \"\", \"Color:=\", \"(143 175 143)\", \"Transparency:=\", 0, \"PartCoordinateSystem:=\",  _\n")
        write(file, "\"Global\", \"UDMId:=\", \"\", \"MaterialValue:=\", \"\" & Chr(34) & \"pec\" & Chr(34) & \"\", \"SurfaceMaterialValue:=\",  _\n")
        write(file, "\"\" & Chr(34) & \"\" & Chr(34) & \"\", \"SolveInside:=\", false, \"ShellElement:=\",  _\n")
        write(file, "false, \"ShellElementThickness:=\", \"0mm\", \"IsMaterialEditable:=\", true, \"UseMaterialAppearance:=\",  _\n")
        write(file, "false, \"IsLightweight:=\", false)\n")
        write(file, "oEditor.ChangeProperty Array(\"NAME:AllTabs\", Array(\"NAME:Geometry3DAttributeTab\", Array(\"NAME:PropServers\",  _\n")
        write(file, "\"Cylinder1\"), Array(\"NAME:ChangedProps\", Array(\"NAME:Name\", \"Value:=\", \"CoaxPin\"))))\n")
        write(file, "oEditor.CreateCylinder Array(\"NAME:CylinderParameters\", \"XCenter:=\", \"$(XPosition)mm\", \"YCenter:=\",  _\n")
        write(file, "\"$(YPosition)mm\", \"ZCenter:=\", \"0mm\", \"Radius:=\", \"$(PinRadius)mm\", \"Height:=\", \"$(SubstrateHeight)mm\", \"WhichAxis:=\",  _\n")
        write(file, "\"Z\", \"NumSides:=\", \"0\"), Array(\"NAME:Attributes\", \"Name:=\", \"Cylinder1\", \"Flags:=\",  _\n")
        write(file, "\"\", \"Color:=\", \"(143 175 143)\", \"Transparency:=\", 0, \"PartCoordinateSystem:=\",  _\n")
        write(file, "\"Global\", \"UDMId:=\", \"\", \"MaterialValue:=\", \"\" & Chr(34) & \"vacuum\" & Chr(34) & \"\", \"SurfaceMaterialValue:=\",  _\n")
        write(file, "\"\" & Chr(34) & \"\" & Chr(34) & \"\", \"SolveInside:=\", true, \"ShellElement:=\",  _\n")
        write(file, "false, \"ShellElementThickness:=\", \"0mm\", \"IsMaterialEditable:=\", true, \"UseMaterialAppearance:=\",  _\n")
        write(file, "false, \"IsLightweight:=\", false)\n")
        write(file, "oEditor.ChangeProperty Array(\"NAME:AllTabs\", Array(\"NAME:Geometry3DAttributeTab\", Array(\"NAME:PropServers\",  _\n")
        write(file, "\"Cylinder1\"), Array(\"NAME:ChangedProps\", Array(\"NAME:Name\", \"Value:=\", \"Probe\"), Array(\"NAME:Material\", \"Value:=\",  _\n")
        write(file, "\"\" & Chr(34) & \"pec\" & Chr(34) & \"\"))))\n")
        write(file, "oProject.Save")
        close(file)
    end
end