module create_box 
    export Cbox
    using LaTeXStrings  
    function Cbox(ProjectName::String, VBSfilePath::String, BoxName::String, Transparency::Int64, Medium::String, Xsize::Float64, Ysize::Float64, Zsize::Float64, Zstart::Float64)
        file = open("$(VBSfilePath)\\create_box.vbs", "w")
        write(file, "Dim oAnsoftApp\n")
        write(file, "Dim oDesktop\n")
        write(file, "Dim oProject\n")
        write(file, "Dim oDesign\n")
        write(file, "Dim oEditor\n")
        write(file, "Dim oModule\n")
        write(file, "Set oAnsoftApp = CreateObject(\"AnsoftHfss.HfssScriptInterface\")\n")
        write(file, "Set oDesktop = oAnsoftApp.GetAppDesktop()\n")
        write(file, "oDesktop.RestoreWindow\n")
        write(file, "Set oProject = oDesktop.SetActiveProject(\"$(ProjectName)\")\n")
        write(file, "Set oDesign = oProject.SetActiveDesign(\"HFSSDesign1\")\n")
        write(file, "Set oEditor = oDesign.SetActiveEditor(\"3D Modeler\")\n")
        write(file, "oEditor.CreateBox Array(\"NAME:BoxParameters\", \"XPosition:=\", \"-50mm\", \"YPosition:=\",  _\n")
        write(file, "\"-40mm\", \"ZPosition:=\", \"0mm\", \"XSize:=\", \"130mm\", \"YSize:=\", \"130mm\", \"ZSize:=\",  _\n")
        write(file, "\"50mm\"), Array(\"NAME:Attributes\", \"Name:=\", \"Box1\", \"Flags:=\", \"\", \"Color:=\",  _\n")
        write(file, "\"(143 175 143)\", \"Transparency:=\", 0, \"PartCoordinateSystem:=\", \"Global\", \"UDMId:=\",  _\n")
        write(file, "\"\", \"MaterialValue:=\", \"\" & Chr(34) & \"vacuum\" & Chr(34) & \"\", \"SurfaceMaterialValue:=\",  _\n")
        write(file, "\"\" & Chr(34) & \"\" & Chr(34) & \"\", \"SolveInside:=\", true, \"ShellElement:=\",  _\n")
        write(file, "false, \"ShellElementThickness:=\", \"0mm\", \"ReferenceTemperature:=\", \"20cel\", \"IsMaterialEditable:=\",  _\n")
        write(file, "true, \"UseMaterialAppearance:=\", false, \"IsLightweight:=\", false)\n")
        write(file, "Set oEditor = oDesign.SetActiveEditor(\"3D Modeler\")\n")
        write(file, "oEditor.ChangeProperty Array(\"NAME:AllTabs\", Array(\"NAME:Geometry3DAttributeTab\", Array(\"NAME:PropServers\",  _\n")
        write(file, "\"Box1\"), Array(\"NAME:ChangedProps\", Array(\"NAME:Name\", \"Value:=\", \"$(BoxName)\"), Array(\"NAME:Material\", \"Value:=\",  _\n")
        write(file, "\"\" & Chr(34) & \"$(Medium)\" & Chr(34) & \"\"), Array(\"NAME:Transparent\", \"Value:=\", $(Transparency)))))\n")
        write(file, "oEditor.ChangeProperty Array(\"NAME:AllTabs\", Array(\"NAME:Geometry3DCmdTab\", Array(\"NAME:PropServers\",  _\n")
        write(file, "\"$(BoxName):CreateBox:1\"), Array(\"NAME:ChangedProps\", Array(\"NAME:Position\", \"X:=\", \"-$(Xsize/2)mm\", \"Y:=\",  _\n")
        write(file, "\"-$(Ysize/2)mm\", \"Z:=\", \"$(Zstart)mm\"), Array(\"NAME:XSize\", \"Value:=\", \"$(Xsize)mm\"), Array(\"NAME:YSize\", \"Value:=\",  _\n")
        write(file, "\"$(Ysize)mm\"), Array(\"NAME:ZSize\", \"Value:=\", \"$(Zsize)mm\"))))\n")
        close(file)
    end
end