module inf_gnd 
    export InfGnd
    using LaTeXStrings  
    function InfGnd(ProjectName::String, VBSfilePath::String, XSize::Float64, YSize::Float64, Transparency::Float64, XPosition::Float64, YPosition::Float64, CoaxRadius::Float64)
        file = open("$(VBSfilePath)\\inf_gnd.vbs", "w")
        write(file, "Dim oAnsoftApp\n")
        write(file, "Dim oDesktop\n")
        write(file, "Dim oProject\n")
        write(file, "Dim oDesign\n")
        write(file, "Dim oEditor\n")
        write(file, "Dim oModule\n")
        write(file, "Set oAnsoftApp = CreateObject(\"Ansoft.ElectronicsDesktop\")\n")
        write(file, "Set oDesktop = oAnsoftApp.GetAppDesktop()\n")
        write(file, "oDesktop.RestoreWindow\n")
        write(file, "Set oProject = oDesktop.SetActiveProject(\"$(ProjectName)\")\n")
        write(file, "Set oDesign = oProject.SetActiveDesign(\"HFSSDesign1\")\n")
        write(file, "Set oEditor = oDesign.SetActiveEditor(\"3D Modeler\")\n")
        write(file, "oEditor.CreateRectangle Array(\"NAME:RectangleParameters\", \"IsCovered:=\", true, \"XStart:=\",  _\n")
        write(file, "\"$(XSize/2)mm\", \"YStart:=\", \"-$(YSize/2)mm\", \"ZStart:=\", \"0mm\", \"Width:=\", \"-$(XSize)mm\", \"Height:=\",  _\n")
        write(file, "\"$(YSize)mm\", \"WhichAxis:=\", \"Z\"), Array(\"NAME:Attributes\", \"Name:=\", \"Rectangle1\", \"Flags:=\",  _\n") 
        write(file, "\"\", \"Color:=\", \"(143 175 143)\", \"Transparency:=\", 0, \"PartCoordinateSystem:=\",  _\n")
        write(file, "\"Global\", \"UDMId:=\", \"\", \"MaterialValue:=\", \"\" & Chr(34) & \"vacuum\" & Chr(34) & \"\", \"SurfaceMaterialValue:=\",  _\n")
        write(file, "\"\" & Chr(34) & \"\" & Chr(34) & \"\", \"SolveInside:=\", true, \"ShellElement:=\",  _\n")
        write(file, " false, \"ShellElementThickness:=\", \"0mm\", \"IsMaterialEditable:=\", true, \"UseMaterialAppearance:=\",  _\n")
        write(file, "false, \"IsLightweight:=\", false)\n")
        write(file, "oEditor.ChangeProperty Array(\"NAME:AllTabs\", Array(\"NAME:Geometry3DAttributeTab\", Array(\"NAME:PropServers\",  _\n")
        write(file, "\"Rectangle1\"), Array(\"NAME:ChangedProps\", Array(\"NAME:Name\", \"Value:=\", \"Inf_GND\"), Array(\"NAME:Transparent\", \"Value:=\",  _\n")
        write(file, "$(Transparency)))))\n")
        write(file, "Set oModule = oDesign.GetModule(\"BoundarySetup\")\n")
        write(file, "oModule.AssignPerfectE Array(\"NAME:PerfE_Inf_GND\", \"Objects:=\", Array(\"Inf_GND\"), \"InfGroundPlane:=\", true)\n")
        write(file, "oEditor.CreateCircle Array(\"NAME:CircleParameters\", \"IsCovered:=\", true, \"XCenter:=\",  _\n")
        write(file, "\"$(XPosition)mm\", \"YCenter:=\", \"$(YPosition)mm\", \"ZCenter:=\", \"0mm\", \"Radius:=\", \"$(CoaxRadius)mm\", \"WhichAxis:=\",  _\n")
        write(file, "\"Z\", \"NumSegments:=\", \"0\"), Array(\"NAME:Attributes\", \"Name:=\", \"Circle1\", \"Flags:=\",  _\n")
        write(file, "\"\", \"Color:=\", \"(143 175 143)\", \"Transparency:=\", 0, \"PartCoordinateSystem:=\",  _\n")
        write(file, "\"Global\", \"UDMId:=\", \"\", \"MaterialValue:=\", \"\" & Chr(34) & \"vacuum\" & Chr(34) & \"\", \"SurfaceMaterialValue:=\",  _\n")
        write(file, "\"\" & Chr(34) & \"\" & Chr(34) & \"\", \"SolveInside:=\", true, \"ShellElement:=\",  _\n")
        write(file, "false, \"ShellElementThickness:=\", \"0mm\", \"IsMaterialEditable:=\", true, \"UseMaterialAppearance:=\",  _\n")
        write(file, "false, \"IsLightweight:=\", false)\n")
        write(file, "oEditor.ChangeProperty Array(\"NAME:AllTabs\", Array(\"NAME:Geometry3DAttributeTab\", Array(\"NAME:PropServers\",  _\n")
        write(file, "\"Circle1\"), Array(\"NAME:ChangedProps\", Array(\"NAME:Name\", \"Value:=\", \"Cutout\"))))\n")
        write(file, "oEditor.Subtract Array(\"NAME:Selections\", \"Blank Parts:=\", \"Inf_GND\", \"Tool Parts:=\",  _\n")
        write(file, "\"Cutout\"), Array(\"NAME:SubtractParameters\", \"KeepOriginals:=\", false)\n")
        write(file, "oProject.Save")
        close(file)
    end
end